name: Pre-build dev container image
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Pre-build dev container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nsqlite/nsqlitedc
          imageTag: ${{ github.sha }}, latest
          push: always
